dbt_training:
  outputs:
    dev:
      account: etbcrxm-mu76076
      database: analytics_dev
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: sysadmin
      schema: gl
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: compute_wh
    ci:
      account: etbcrxm-mu76076
      database: analytics_dev
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: sysadmin
      schema: ci # QA/UAT/Etc. this will create a ci schema to test
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: compute_wh
    prod:
      account: etbcrxm-mu76076
      database: analytics
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: sysadmin
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: compute_wh
  target: dev